### ISSUE TITLE
ERROR: No matching distribution found for entropy>=0.9

### ISSUE THREAD

**Issue by driverCzn** [fkie-cad/common_helper_unpacking_classifier#2]
Hello, I encountered this problem when installing FACT.
It seems that [entropy 0.9](https://pypi.org/project/entropy/0.9/) no longer exists.
I guess it may be replaced by another pypi package?

**Comment by dorpvom** [comment]
Hi. We can confirm the problem. The project does indeed not exist anymore, at least on pypi. We are currently developing an own solution at `fkie-cad/entropython` which should be plugged in for the lost project as soon as possible.

**Comment by dorpvom** [comment]
In the meantime, I don't really have an idea how to solve this cleanly. A possible solution would be to remove entropy from the dependencies and mock the function call to always return some fixed float in the [0.0, 1.0] interval. But that's quite destructive and I don't want to do this on our main branch

**Comment by driverCzn** [comment]
Hi, I find the backup repo https://github.com/armbues/python-entropy.
As a workaround, maybe you can fork the repo and install the forked python-entropy first when installing 
common_helper_unpacking_classifier.

**Comment by dorpvom** [comment]
Thanks for the hint. I think @jstucke should have fixed the installation for now (seems we already shipped an alternative). In the coming weeks we will replace the python implementation of the shannon entropy by a rust implementation to speed it up again.

**Comment by driverCzn** [comment]
Oh rust, nice~

**Comment by jstucke** [comment]
There was another problem with the installation of a dependency (seems like the old syntax is deprecated now), but it seems to work now (at least the travis build was successful).

**Comment by jstucke** [comment]
Thanks to @Enkelmann  we now have the new rust-based entropy package, so everything should work for now. I will close this issue. Please feel free to reopen it if anything still fails.
